[0.042s] Invoking command in '/home/matrix/ros2_ws/build/custom_msg': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/matrix/ros2_ws/src/custom_msg -DCMAKE_INSTALL_PREFIX=/home/matrix/ros2_ws/install/custom_msg
[0.111s] -- Found ament_cmake: 1.3.11 (/opt/ros/humble/share/ament_cmake/cmake)
[0.438s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.439s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.449s] -- Found rosidl_adapter: 3.1.6 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.530s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.610s] -- Found std_msgs: 4.2.4 (/opt/ros/humble/share/std_msgs/cmake)
[1.102s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.102s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.102s]   custom_msg --arguments-file
[1.103s]   /home/matrix/ros2_ws/build/custom_msg/rosidl_adapter__arguments__custom_msg.json
[1.103s]   --output-dir
[1.103s]   /home/matrix/ros2_ws/build/custom_msg/rosidl_adapter/custom_msg
[1.103s]   --output-file
[1.104s]   /home/matrix/ros2_ws/build/custom_msg/rosidl_adapter/custom_msg.idls)
[1.104s]   returned error code 1:
[1.104s] 
[1.104s]   Traceback (most recent call last):
[1.105s] 
[1.105s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[1.105s]       return _run_code(code, main_globals, None,
[1.105s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[1.106s]       exec(code, run_globals)
[1.106s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.106s]       sys.exit(main())
[1.107s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.107s]       abs_idl_file = convert_to_idl(
[1.107s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.107s]       return convert_msg_to_idl(
[1.109s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.109s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.109s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[1.109s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[1.110s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[1.110s]       self.base_type = BaseType(
[1.110s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[1.110s]       raise InvalidResourceName(
[1.111s] 
[1.111s]   rosidl_adapter.parser.InvalidResourceName: 'age' is an invalid message
[1.111s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.111s] 
[1.112s] Call Stack (most recent call first):
[1.112s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.112s]   CMakeLists.txt:13 (rosidl_generate_interfaces)
[1.112s] 
[1.112s] [0m
[1.113s] -- Configuring incomplete, errors occurred!
[1.113s] See also "/home/matrix/ros2_ws/build/custom_msg/CMakeFiles/CMakeOutput.log".
[1.124s] Invoked command in '/home/matrix/ros2_ws/build/custom_msg' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/matrix/ros2_ws/src/custom_msg -DCMAKE_INSTALL_PREFIX=/home/matrix/ros2_ws/install/custom_msg
